name: "CI/CD Pipeline"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Workflow_Practice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: List files
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Build project (push events only)
        if: github.event_name == 'push'
        run: npm run build

      - name: Upload build artifact (push events only)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: Workflow_Practice/dist/

  cd:
    needs: ci
    if: github.event_name == 'push' && needs.ci.result == 'success'
    runs-on: ubuntu-latest
    # Remove the working-directory default for this job
    # so we can control the paths more precisely

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./  # Download to the root of the workspace

      - name: Verify downloaded files
        run: |
          echo "Contents of root directory:"
          ls -la
          echo "Contents of Workflow_Practice directory:"
          ls -la Workflow_Practice/

      - name: Move artifact to correct location
        run: |
          # Move the downloaded dist folder to the correct location
          mv dist/ Workflow_Practice/dist/
          echo "After moving:"
          ls -la Workflow_Practice/

      - name: Deploy to server
        run: echo "🚀 Deploying application..."